apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: qemu-user-static
  namespace: qemu-user-static
  annotations: {}
  labels:
    app: qemu-user-static
    app.kubernetes.io/component: qemu-user-static
    app.kubernetes.io/instance: qemu-user-static
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: multiarch/qemu-user-static:register
    from:
      kind: DockerImage
      name: multiarch/qemu-user-static:register
    generation: 2
    importPolicy: {}
    name: register
    referencePolicy:
      type: Source
